<?php
require_once __DIR__.'/includes/auth.php'; requireLogin();
require_once __DIR__.'/config/db.php';
if (empty($_SESSION['csrf_module3'])) $_SESSION['csrf_module3']=bin2hex(random_bytes(24));
$csrf=$_SESSION['csrf_module3'];
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$counts=[]; foreach(['HOSPITAL','DEPARTMENT','BED','DOCTOR','ADMISSION_RESERVATION','ESCALATION_LOG'] as $t) $counts[$t]=(int)$pdo->query("SELECT COUNT(*) FROM `$t`")->fetchColumn();
$hospitals=$pdo->query('SELECT * FROM HOSPITAL ORDER BY hospital_name')->fetchAll();
$departments=$pdo->query('SELECT d.*,h.hospital_name FROM DEPARTMENT d JOIN HOSPITAL h ON h.hospital_id=d.hospital_id ORDER BY h.hospital_name,d.department_name')->fetchAll();
$beds=$pdo->query('SELECT b.*,d.department_name,h.hospital_name FROM BED b JOIN DEPARTMENT d ON d.department_id=b.department_id JOIN HOSPITAL h ON h.hospital_id=d.hospital_id ORDER BY h.hospital_name,d.department_name,b.bed_no')->fetchAll();
$doctors=$pdo->query('SELECT dr.*,d.department_name,h.hospital_name FROM DOCTOR dr JOIN DEPARTMENT d ON d.department_id=dr.department_id JOIN HOSPITAL h ON h.hospital_id=d.hospital_id ORDER BY h.hospital_name,d.department_name,dr.doctor_name')->fetchAll();
$reservations=$pdo->query('SELECT ar.*,er.patient_condition,b.bed_no,d.department_name,h.hospital_name,dr.doctor_name FROM ADMISSION_RESERVATION ar JOIN EMERGENCY_REQUEST er ON er.emergency_request_id=ar.emergency_request_id JOIN BED b ON b.bed_id=ar.bed_id JOIN DEPARTMENT d ON d.department_id=b.department_id JOIN HOSPITAL h ON h.hospital_id=d.hospital_id LEFT JOIN DOCTOR dr ON dr.doctor_id=ar.doctor_id ORDER BY ar.reservation_time DESC')->fetchAll();
$escalations=$pdo->query('SELECT el.*,er.patient_condition,u.full_name FROM ESCALATION_LOG el JOIN EMERGENCY_REQUEST er ON er.emergency_request_id=el.emergency_request_id LEFT JOIN `USER` u ON u.user_id=el.handled_by ORDER BY el.escalation_time DESC LIMIT 20')->fetchAll();
$availableBeds=array_filter($beds,fn($x)=>$x['status']==='Available');
$onDutyDoctors=array_filter($doctors,fn($x)=>$x['duty_status']==='On Duty');
$activeRequests=$pdo->query("SELECT emergency_request_id,request_type,patient_condition,priority_level FROM EMERGENCY_REQUEST WHERE status IN('Submitted','Pending','Searching','Assigned') ORDER BY request_time DESC")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hospital Resources | EmergencyLink</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f1f5f9;color:#17324d;font-family:Arial,sans-serif}.top{background:linear-gradient(120deg,#073b5c,#087f7b);color:#fff;padding:22px 5%}.top div{max-width:1250px;margin:auto;display:flex;align-items:center;justify-content:space-between}.top a{color:#fff;text-decoration:none}.wrap{max-width:1250px;margin:28px auto;padding:0 18px}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:22px}.hero h1{margin:0;font-size:32px}.hero p{margin:7px 0 0;color:#64748b}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.stat,.panel{background:#fff;border-radius:15px;box-shadow:0 8px 25px #17324d14}.stat{padding:18px;border-top:4px solid #0d9488}.stat span{display:block;color:#64748b;font-size:12px;font-weight:bold}.stat strong{font-size:29px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:20px}.panel{padding:20px}.panel h2{margin:0 0 15px}.full{grid-column:1/-1}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.form-grid .wide{grid-column:1/-1}input,select,textarea{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}label{font-size:12px;font-weight:bold;color:#475569}button{border:0;border-radius:8px;padding:10px 15px;background:#087f7b;color:#fff;font-weight:bold;cursor:pointer}.danger{background:#dc3545}.secondary{background:#2563eb}.small{padding:6px 9px;font-size:11px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #e2e8f0}th{background:#f8fafc}.badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-weight:bold;font-size:11px}.Available,.Confirmed,.On-Duty{background:#dcfce7;color:#15803d}.Reserved,.Assigned{background:#fef3c7;color:#a16207}.Completed{background:#dbeafe;color:#1d4ed8}.Cancelled,.Maintenance,.Off-Duty{background:#fee2e2;color:#b91c1c}.alert{padding:13px 16px;border-radius:9px;margin-bottom:17px}.success{background:#dcfce7;color:#166534}.error{background:#fee2e2;color:#991b1b}.actions{display:flex;gap:6px;flex-wrap:wrap}@media(max-width:950px){.stats{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}.full{grid-column:auto}}@media(max-width:600px){.stats,.form-grid{grid-template-columns:1fr}.wide{grid-column:auto!important}.hero{display:block}}
</style></head><body>
<header class="top"><div><strong>🏥 EmergencyLink · Hospital Resources</strong><nav><a href="index.php">Integrated Home</a> &nbsp; <a href="logout.php">Logout</a></nav></div></header>
<main class="wrap"><section class="hero"><div><h1>Hospital Resource Management</h1><p>Manage facilities, availability, admissions and emergency escalation.</p></div></section>
<?php if(!empty($_GET['msg'])):?><div class="alert <?=($_GET['type']??'')==='error'?'error':'success'?>"><?=h($_GET['msg'])?></div><?php endif;?>
<section class="stats"><?php foreach($counts as $name=>$count):?><div class="stat"><span><?=h(str_replace('_',' ',$name))?></span><strong><?=$count?></strong></div><?php endforeach;?></section>

<section class="grid">
<div class="panel"><h2>Add Hospital</h2><form class="form-grid" method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="add_hospital"><label>Name<input name="name" required></label><label>Location<input name="location" required></label><label>Contact<input name="contact" required></label><label>Address<input name="address" required></label><button class="wide">Add Hospital</button></form></div>
<div class="panel"><h2>Add Department</h2><form class="form-grid" method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="add_department"><label>Name<input name="name" required></label><label>Hospital<select name="hospital_id" required><?php foreach($hospitals as $x):?><option value="<?=$x['hospital_id']?>"><?=h($x['hospital_name'])?></option><?php endforeach;?></select></label><label>Floor<input type="number" name="floor" min="0" required></label><label>Contact<input name="contact"></label><button class="wide">Add Department</button></form></div>
<div class="panel"><h2>Add Bed</h2><form class="form-grid" method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="add_bed"><label>Bed Number<input name="bed_no" required></label><label>Bed Type<input name="bed_type" placeholder="General / ICU" required></label><label class="wide">Department<select name="department_id" required><?php foreach($departments as $x):?><option value="<?=$x['department_id']?>"><?=h($x['hospital_name'].' — '.$x['department_name'])?></option><?php endforeach;?></select></label><button class="wide">Add Bed</button></form></div>
<div class="panel"><h2>Add Doctor</h2><form class="form-grid" method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="add_doctor"><label>Name<input name="name" required></label><label>Contact<input name="contact" required></label><label>Specialization<input name="specialization" required></label><label>Department<select name="department_id" required><?php foreach($departments as $x):?><option value="<?=$x['department_id']?>"><?=h($x['hospital_name'].' — '.$x['department_name'])?></option><?php endforeach;?></select></label><button class="wide">Add Doctor</button></form></div>

<div class="panel full"><h2>Create Admission Reservation</h2><form class="form-grid" method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="reserve"><label>Patient Condition<input name="condition" required></label><label>Pickup Location<input name="pickup" required></label><label>Priority<select name="priority"><option>Low</option><option selected>Medium</option><option>High</option><option>Critical</option></select></label><label>Available Bed<select name="bed_id" required><?php foreach($availableBeds as $x):?><option value="<?=$x['bed_id']?>"><?=h($x['hospital_name'].' — '.$x['department_name'].' — '.$x['bed_no'])?></option><?php endforeach;?></select></label><label>On-duty Doctor<select name="doctor_id" required><?php foreach($onDutyDoctors as $x):?><option value="<?=$x['doctor_id']?>"><?=h($x['hospital_name'].' — '.$x['department_name'].' — '.$x['doctor_name'])?></option><?php endforeach;?></select></label><label>Notes<input name="notes"></label><button class="wide secondary">Confirm Admission Reservation</button></form></div>

<div class="panel full"><h2>Resource Availability</h2><table><thead><tr><th>Hospital</th><th>Department</th><th>Resource</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($beds as $x):?><tr><td><?=h($x['hospital_name'])?></td><td><?=h($x['department_name'])?></td><td>Bed <?=h($x['bed_no'].' · '.$x['bed_type'])?></td><td><span class="badge <?=h(str_replace(' ','-',$x['status']))?>"><?=h($x['status'])?></span></td><td><?php if(!in_array($x['status'],['Reserved','Occupied'])):?><form method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="toggle_bed"><input type="hidden" name="bed_id" value="<?=$x['bed_id']?>"><button class="small">Toggle Maintenance</button></form><?php endif;?></td></tr><?php endforeach;?><?php foreach($doctors as $x):?><tr><td><?=h($x['hospital_name'])?></td><td><?=h($x['department_name'])?></td><td><?=h($x['doctor_name'].' · '.$x['specialization'])?></td><td><span class="badge <?=h(str_replace(' ','-',$x['duty_status']))?>"><?=h($x['duty_status'])?></span></td><td><form method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="toggle_doctor"><input type="hidden" name="doctor_id" value="<?=$x['doctor_id']?>"><button class="small">Toggle Duty</button></form></td></tr><?php endforeach;?></tbody></table></div>

<div class="panel full"><h2>Admission Reservations</h2><table><thead><tr><th>ID</th><th>Patient</th><th>Hospital / Bed</th><th>Doctor</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($reservations as $x):?><tr><td>#<?=$x['reservation_id']?></td><td><?=h($x['patient_condition'])?></td><td><?=h($x['hospital_name'].' · '.$x['department_name'].' · '.$x['bed_no'])?></td><td><?=h($x['doctor_name']?:'Not assigned')?></td><td><span class="badge <?=h($x['status'])?>"><?=h($x['status'])?></span></td><td class="actions"><?php if(in_array($x['status'],['Pending','Confirmed'])): foreach(['Completed'=>'secondary','Cancelled'=>'danger'] as $status=>$class):?><form method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="reservation_status"><input type="hidden" name="reservation_id" value="<?=$x['reservation_id']?>"><input type="hidden" name="new_status" value="<?=$status?>"><button class="small <?=$class?>"><?=$status?></button></form><?php endforeach; endif;?></td></tr><?php endforeach;?><?php if(!$reservations):?><tr><td colspan="6">No admission reservations yet.</td></tr><?php endif;?></tbody></table></div>

<div class="panel"><h2>Record Escalation</h2><form class="form-grid" method="post" action="module3_action.php"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="escalate"><label class="wide">Active Request<select name="request_id" required><?php foreach($activeRequests as $x):?><option value="<?=$x['emergency_request_id']?>">#<?=$x['emergency_request_id']?> · <?=h($x['request_type'].' · '.$x['patient_condition'])?></option><?php endforeach;?></select></label><label>Level<select name="level"><option>1</option><option>2</option><option>3</option></select></label><label>Reason<input name="reason" required></label><label class="wide">Remarks<textarea name="remarks"></textarea></label><button class="wide danger">Record Escalation</button></form></div>
<div class="panel"><h2>Escalation History</h2><table><thead><tr><th>Request</th><th>Level</th><th>Reason</th><th>Handled By</th></tr></thead><tbody><?php foreach($escalations as $x):?><tr><td>#<?=$x['emergency_request_id']?></td><td><?=$x['escalation_level']?></td><td><?=h($x['reason'])?></td><td><?=h($x['full_name']?:'System')?></td></tr><?php endforeach;?><?php if(!$escalations):?><tr><td colspan="4">No escalations recorded.</td></tr><?php endif;?></tbody></table></div>
</section></main></body></html>
